-- Disable Row Level Security on all WMS tables
-- RLS was enabled without policies, causing empty query results

ALTER TABLE IF EXISTS wms_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_case_labels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_cycle_counts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_repacks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_pick_lists DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_pick_list_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_dispatch_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_delivery_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_dispatch_batch_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_pallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_pallet_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_storage_charges DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wms_partner_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consignment_settlements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consignment_settlement_items DISABLE ROW LEVEL SECURITY;
