/**
 * This file was auto-generated by openapi-typescript. Do not make direct
 * changes to the file.
 */

export interface paths {
  '/CultxActiveMarkets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get active wine markets
     *
     * Returns a paginated list of active wine markets with trading information
     */
    get: operations['getActiveMarkets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    WineMarket: {
      /**
       * Wine region
       *
       * @example
       *   Bordeaux;
       */
      region: string;
      /**
       * Wine producer/estate name
       *
       * @example
       *   Château Lafite Rothschild
       */
      producer: string;
      /**
       * Full name of the wine
       *
       * @example
       *   Château Lafite Rothschild, Pauillac, 1er Cru Classé
       */
      wineName: string;
      /**
       * Vintage year
       *
       * @example
       *   2015;
       */
      vintage: number;
      /**
       * Number of units in a lot
       *
       * @example
       *   12;
       */
      unitCount: number;
      /**
       * Size of each unit
       *
       * @example
       *   75cl
       */
      unitSize: string;
      /**
       * LWIN18 identifier (unique wine identifier)
       *
       * @example
       *   1014223;
       */
      lwin18: string;
      /**
       * Format: double
       *
       * Current market value
       *
       * @example
       *   5250;
       */
      marketValue: number;
      /**
       * Format: double
       *
       * Wine rating/score
       *
       * @example
       *   97.5;
       */
      score?: number | null;
      /**
       * Available quantity for trading
       *
       * @example
       *   120;
       */
      availableQuantity: number;
      highestBid?: {
        /**
         * Format: double
         *
         * Highest bid price
         */
        price: number;
        /** Quantity at highest bid */
        quantity: number;
      } | null;
      lowestOffer?: {
        /**
         * Format: double
         *
         * Lowest offer price
         */
        price: number;
        /** Quantity at lowest offer */
        quantity: number;
        /** Order identifier */
        orderId: string;
      } | null;
      /**
       * Format: date-time
       *
       * Date and time of last trade
       *
       * @example
       *   2024-01-15T14:30:00Z
       */
      lastTradeDateTime?: string | null;
      /**
       * Format: double
       *
       * Price of last trade
       *
       * @example
       *   5200;
       */
      lastTradePrice?: number | null;
      /**
       * Format: double
       *
       * Spread between bid and offer
       *
       * @example
       *   50;
       */
      spread?: number | null;
      /**
       * Filename of wine image
       *
       * @example
       *   lafite-2015.jpg
       */
      imageFileName?: string | null;
      /**
       * Product URN identifier
       *
       * @example
       *   urn: product: wine: 1014223;
       */
      productUrn: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getActiveMarkets: {
    parameters: {
      query: {
        /** Page number for pagination (0-indexed) */
        page: number;
        /** Number of items per page */
        pageSize: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** Successful response with active markets data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data: components['schemas']['WineMarket'][];
            /**
             * Total number of wine markets available
             *
             * @example
             *   3522;
             */
            count: number;
          };
        };
      };
      /** Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
